/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        'custom-green': '#F0F8F0',
        'dark-blue' : '#25A6E0',
        'light-blue' : '#BDE8FC',
        'on-background': "#191c1e",
        'on-tertiary': "#ffffff",
        'tertiary-fixed-dim': "#bcc7de",
        'outline-variant': "#bdc8d1",
        'on-error-container': "#93000a",
        'secondary': "#576065",
        'on-secondary-fixed': "#141d21",
        'secondary-container': "#dbe4ea",
        'primary-container': "#00adef",
        'primary-fixed-dim': "#83cfff",
        'tertiary-container': "#97a2b9",
        'on-primary-fixed-variant': "#004c6c",
        'surface-bright': "#f7f9fb",
        'on-surface': "#191c1e",
        'surface-container-lowest': "#ffffff",
        'secondary-fixed-dim': "#bfc8ce",
        'surface-tint': "#00658d",
        'inverse-primary': "#83cfff",
        'surface-dim': "#d8dadc",
        'error-container': "#ffdad6",
        'primary': "#00658d",
        'outline': "#6e7881",
        'tertiary-fixed': "#d8e3fb",
        'error': "#ba1a1a",
        'inverse-surface': "#2d3133",
        'surface-variant': "#e0e3e5",
        'surface-container': "#eceef0",
        'on-error': "#ffffff",
        'on-tertiary-fixed-variant': "#3c475a",
        'primary-fixed': "#c6e7ff",
        'surface-container-high': "#e6e8ea",
        'surface-container-highest': "#e0e3e5",
        'secondary-fixed': "#dbe4ea",
        'on-primary-container': "#003d57",
        'on-surface-variant': "#3e4850",
        'on-secondary-container': "#5d666b",
        'inverse-on-surface': "#eff1f3",
        'tertiary': "#545f73",
        'on-tertiary-fixed': "#111c2d",
        'surface-container-low': "#f2f4f6",
        'on-secondary-fixed-variant': "#3f484d",
        'on-tertiary-container': "#2e394b",
        'on-secondary': "#ffffff",
        'on-primary-fixed': "#001e2e",
        'surface': "#f7f9fb",
        'background': "#f7f9fb",
        'on-primary': "#ffffff"
      },
      fontFamily: {
        waterfall: ['Waterfall', 'sans-serif'],
        serif: ['"Source Serif 4"', 'Georgia', 'ui-serif', 'serif'],
        sans: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
