import "./globals.css";
import NavBar from "./navbar/NavBar";
import Footer from "./footer/Footer";
import Providers from "./providers";

export const metadata = {
  title: "Noteshaala",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className="bg-slate-100">
        <Providers>
          <NavBar/>
            {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
